######################################################################
##
## Filename: func_gen_tb.udo
## Created on: Wed Feb 07 12:51:51 PM Hawaiian Standard Time 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
log -r /*
do wave.do