######################################################################
##
## Filename: hw2_tb.udo
## Created on: Thu Feb 15 8:47:43 PM Hawaiian Standard Time 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
log -r /*
do wave1.do